### ISSUE TITLE
async onExit handler

### ISSUE THREAD

**Issue by GO-DIE** [tapjs/signal-exit#70]
Add async onExit handler feature.

```ts
onExit(async function () {
    console.log('signalExit: closing app server');
    await app.close();
    console.log('App closed');
 });
```
when code run, it log 'signalExit: closing app server' but not log 'App closed'. The app.close() is not normal close.
I need async onExit handler to close app which is to close the db connect. This is the graceful exit behavior of the program.

**Comment by isaacs** [comment]
Unfortunately, because this module aims to be as complete as possible in what it captures (ie, every possible route to exit except uncatchable `SIGKILL`), it runs these handlers _after_ the event loop may already have been torn down.  And since the goal is to still exit in the same way as it would have normally (ie, with the same error code _and the same signal_) it forcibly applies the fatal signal if it is the only listener.

All that means, you get exactly one tick to do whatever you need to do, I'm afraid.

The best thing to do is attach your listener on `process.on('beforeExit')` and assign handlers to all of the potentially fatal signals.  You can get that list by pulling in the `signals` module that this library exports.

(I did just now take a pass at trying to get async `onExit` handling working, but it's just not possible, sorry.)
